- name: install unzip
  package:
    name: unzip

- name: install curl
  package:
    name: curl

- name: install bat
  apt:
    name: bat

- name: install neofetch
  apt:
    name: neofetch    

- name: install git
  package:
    name: git

- name: Gnome Software
  apt:
    name: gnome-software
  when: ansible_distribution == "Ubuntu"

- name: Software Flatpak Plugin
  apt:
    name: gnome-software-plugin-flatpak
  when: ansible_distribution == "Ubuntu"

- name: Software Snap Plugin
  apt:
    name: gnome-software-plugin-snapd
  when: ansible_distribution == "Ubuntu"

- name: install tree 
  package:
    name: tree
    state: latest

- name: install flatpak 
  package:
    name: flatpak
    state: latest
    
- name: Install Sticky Notes
  community.general.flatpak:
    name: https://dl.flathub.org/repo/appstream/com.vixalien.sticky.flatpakref
    state: present

- name: Install Visual Studio Code .deb package
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Install 1Password .deb package
  ansible.builtin.apt:
    deb: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb


# Begin Google Chrome Install

- name: Install apt-transport-https
  ansible.builtin.apt:
    state: latest
    update_cache: true

- name: Add APT signing key
  ansible.builtin.apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install google-chrome-stable
  ansible.builtin.apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true

# End Google Chrome Install    
