- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: install tree 
  package:
    name: tree
    state: latest

- name: install flatpak 
  package:
    name: flatpak
    state: latest
    
- name: Install Sticky Notes
  community.general.flatpak:
    name: https://dl.flathub.org/repo/appstream/com.vixalien.sticky.flatpakref
    state: present

- name: Install Visual Studio Code .deb package
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Install 1Password .deb package
  ansible.builtin.apt:
    deb: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb


# Begin Google Chrome Install

- name: Install apt-transport-https
  ansible.builtin.apt:
    state: latest
    update_cache: true

- name: Add APT signing key
  ansible.builtin.apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install google-chrome-stable
  ansible.builtin.apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true

# End Google Chrome Install    
